### ISSUE TITLE
Integrate estimation-specific data preprocessing into fit() and predict() methods

### ISSUE THREAD

**Issue by johaupt** [socket778/XBCF#1]
Following the tutorials it is necessary to standardize the target variable `y` before calling `.fit()` and to unstandardize the raw prediction collected from `.predict()`. I think it would be more convenient to do this automatically and hidden from the user and make the implementation aligned with the scikit-learn standard that the X covariates can be assumed standardized, but not the `y` input.

I've monkey-patched the `XBCF` class to do the processing as in the documentation in this way: 

```
class myXBCF(XBCF):
    def fit(self, x_t, x, y, z, p_cat=0):
        z= z.astype('int32')
        p_cat= int(p_cat)

        self.sdy = np.std(y)
        y = y - np.mean(y)
        y = y / self.sdy
        self.y = y

        super().fit(x_t, x, y, z, p_cat=p_cat)

        return self


    def predict(self, *args,**kwargs):
        tauhats = super().predict(*args,**kwargs)
        
        b = self.b.transpose()
        a = self.a.transpose()

        thats = self.sdy * tauhats * (b[1] - b[0])
        thats_mean = np.mean(thats[:, self.get_params()['burnin']:], axis=1)
        
        return thats_mean
```

I suggest that the original `fit` and `predict` methods be kept as hidden methods `_fit()` and `_predict()` for advanced users and to integrate the processing in the exposed methods. 

Do you agree? If yes I can make a simple PR that includes the preprocessing within the methods and an integer check for `p_cat`, which gives a cryptical error if it is a float.

**Comment by socket778** [comment]
Hi Johannes! Thanks for the message. Yes, your point about standardizing the target variable y is exactly correct and my intention is to add the standardization of it in the source code, so that this change will become effective in both R and python packages. I plan to do this and update the current example scripts by the end of the month, but we can use your solution for the python version right away, if you would like to contribute!

**Comment by johaupt** [comment]
I'll make a PR to add the above process to the python source and I've had a look at the R changes you made. I'll try to be consistent with the steps there and the naming of objects.

**Comment by socket778** [comment]
Sounds good. I just updated the R predict function (https://github.com/socket778/XBCF/blob/master/R/predict.XBCF.R) so that it properly back-scales after performing prediction on the forests. Let me know if you have any questions, and thanks for contributing to the repo!

**Comment by johaupt** [comment]
Finally got around to make a PR to integrate this: #2

**Comment by socket778** [comment]
Thanks Johannes!
