### ISSUE TITLE
Accessing Sigma Draws

### ISSUE THREAD

**Issue by Jakefawkes** [socket778/XBCF#10]
Hello,

I was wondering if there is any way to access the sigma draws in the Python version? Currently the following portion of code which updates the sigma draws is commented out:

```  
if self.model == "Normal":
    self.sigma_draws = self._xbcf_cpp.get_sigma_draws(
                self.params["num_sweeps"] * self.params["num_trees"]
            )
     self.confirm = "Confirm"
     # Convert from colum major
     self.sigma_draws = self.sigma_draws.reshape(
                (self.params["num_sweeps"], self.params["num_trees"]), order="F")
```

I have tried going through the files to see if the sigmas can be easily accessed but am running into some difficulty as it seems to require quite a bit of editing of the C++ files. I wondered if you had any pointers on how to access the sigmas, or why this portion of code is commented out. 

Thank you very much for any help and a great package.

**Comment by socket778** [comment]
Hi Jakefawkes, I'm closing this issue as XBCF has become part of the `StochasticTree` package (available in both Python and R), please visit https://github.com/StochasticTree/stochtree-cpp for the most recent version of the package in case it's still relevant. Sorry for not being able to answer in a timely manner.
