### ISSUE TITLE
Error in getTaus(xbcf.fit) : Can only get taus for an XBCF object

### ISSUE THREAD

**Issue by 0blongata** [socket778/XBCF#8]
Hi there,

I am going through sample code for XBCF() function.

When executing the following two examples exactly as written:
1. example.R (https://github.com/socket778/XBCF/blob/master/example.R),
2. test_xbcf.R (https://github.com/socket778/XBCF/blob/master/tests/test_xbcf.R)

I get the following error when I try to use getTaus() and getMus() on the XBCF object.
1.
> tauhats <- getTaus(fit_xbcf)
Error in getTaus(fit_xbcf) : Can only get taus for an XBCF object.
> muhats <- getMus(fit_xbcf)
Error in getMus(fit_xbcf) : Can only get taus for an XBCF object.
2.
> tauhats <- getTaus(xbcf.fit)
Error in getTaus(xbcf.fit) : Can only get taus for an XBCF object.

Is this issue that you have also encountered?
Also, it looks like one can access the tau or mu estimates for observations with the following:
1. fit_xbcf$tauhats
fit_xbcf$muhats
2. xbcf.fit$muhats

If getTaus() and getMus() is not working, do you know if there is a workaround to estimate the taus and mus for each observation?

Thanks!

**Comment by socket778** [comment]
Hi 0blongata,
Thank you for bringing it up -- there was an issue with object naming that is fixed now. Just a quick note about XBCF: the most recent version of XBCF with binary treatment (XBCFdiscrete) and a version with continuous treatment (XBCFcontinuous) are available in the [XBART](https://github.com/JingyuHe/XBART/) repository.
